FROM ubuntu:16.04

RUN apt-get -yqq update && \
    apt-get -yqq install python python-pip python-requests apache2 \
                         libapache2-mod-wsgi python-setuptools python-lxml \
                         git-core
